### ISSUE TITLE
USB OTG Not Working

### ISSUE THREAD

**Issue by Elepover** [Whyred-Dev/android_kernel_xiaomi_whyred#2]
I'm using a Whyred (4G ram edition), with ResurrectionRemix O 6.1 Official, whose kernel version is 4.4.135-3scanor. Any USB device cannot be detected, neither the apps or the OS. The connector and the device is tested and okay on another device. Is there any missing drivers in the kernel?

**Comment by kirkhan93** [comment]
Can u check with stock kernel...if it broken in kirks , will fix this asap.

**Comment by Elepover** [comment]
Tested. Kernel is okay, it's the system's problem.
